<a href="https://colab.research.google.com/github/sheikhanasmalik/SQL-Practice/blob/main/advance_sql/pivots_using_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql
select orderdate, count(customerkey) as order_count
from sales
group by orderdate
order by orderdate desc
limit 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

    orderdate  order_count
0  2024-04-20           97
1  2024-04-19           50
2  2024-04-18           57
3  2024-04-17           61
4  2024-04-16           32

In [4]:
%%sql
select orderdate, orderkey
from sales
limit 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

    orderdate  orderkey
0  2015-01-01      1000
1  2015-01-01      1000
2  2015-01-01      1001
3  2015-01-01      1002
4  2015-01-01      1002

In [5]:
%%sql
select orderdate, count(distinct customerkey) as order_count
from sales
group by orderdate
order by orderdate desc
limit 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

    orderdate  order_count
0  2024-04-20           35
1  2024-04-19           19
2  2024-04-18           25
3  2024-04-17           22
4  2024-04-16           14

In [6]:
%%sql
select orderdate, count(distinct customerkey) as order_count
from sales
where orderdate between '2024-01-01' and '2024-1-31'
group by orderdate
order by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

31 rows affected.

     orderdate  order_count
0   2024-01-01           40
1   2024-01-02           53
2   2024-01-03           63
3   2024-01-04           71
4   2024-01-05           46
5   2024-01-06           83
6   2024-01-07            8
7   2024-01-08           33
8   2024-01-09           41
9   2024-01-10           53
10  2024-01-11           54
11  2024-01-12           41
12  2024-01-13           65
13  2024-01-14            7
14  2024-01-15           31
15  2024-01-16           41
16  2024-01-17           51
17  2024-01-18           57
18  2024-01-19           39
19  2024-01-20           63
20  2024-01-21            7
21  2024-01-22           29
22  2024-01-23           40
23  2024-01-24           49
24  2024-01-25           56
25  2024-01-26           38
26  2024-01-27           68
27  2024-01-28            7
28  2024-01-29           31
29  2024-01-30           36
30  2024-01-31           52

In [7]:
%%sql
select distinct continent
from customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0      Australia
1  North America
2         Europe

In [8]:
%%sql
select s.orderdate,
       count(distinct s.customerkey) as order_count,
       COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS europe_orders,
       COUNT(DISTINCT CASE WHEN c.continent = 'Asia' THEN s.customerkey END) AS asia_orders,
       COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) AS north_america_orders
from sales s
left join customer c on s.customerkey = c.customerkey
where s.orderdate between '2024-01-01' and '2024-1-31'
group by s.orderdate
order by s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

31 rows affected.

     orderdate  order_count  europe_orders  asia_orders  north_america_orders
0   2024-01-01           40             11            0                    27
1   2024-01-02           53             17            0                    33
2   2024-01-03           63             23            0                    32
3   2024-01-04           71             21            0                    46
4   2024-01-05           46             17            0                    25
5   2024-01-06           83             22            0                    54
6   2024-01-07            8              4            0                     4
7   2024-01-08           33             13            0                    18
8   2024-01-09           41             18            0                    17
9   2024-01-10           53             16            0                    32
10  2024-01-11           54             20            0                    28
11  2024-01-12           41             15            0                    24
12  2024-01-13           65             21            0                    41
13  2024-01-14            7              4            0                     3
14  2024-01-15           31              7            0                    21
15  2024-01-16           41             13            0                    25
16  2024-01-17           51             16            0                    33
17  2024-01-18           57             14            0                    37
18  2024-01-19           39             10            0                    28
19  2024-01-20           63             24            0                    34
20  2024-01-21            7              1            0                     5
21  2024-01-22           29             10            0                    16
22  2024-01-23           40             13            0                    22
23  2024-01-24           49             19            0                    29
24  2024-01-25           56             21            0                    30
25  2024-01-26           38             11            0                    26
26  2024-01-27           68             21            0                    43
27  2024-01-28            7              0            0                     5
28  2024-01-29           31             13            0                    15
29  2024-01-30           36             12            0                    19
30  2024-01-31           52             16            0                    30

In [ ]:
%%sql
select p.categoryname,
sum(s.quantity*s.netprice*s.exchangerate) as total_revenue,
sum(case when s.orderdate between '2024-01-01' and '2024-1-31' then s.quantity*s.netprice*s.exchangerate end) as revenue_2024,
sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate end) as revenue_2023
from sales s
left join product p on s.productkey = p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  total_revenue  revenue_2024  revenue_2023
0                          Audio     5312898.10      68541.81     688690.18
1        Cameras and camcorders     18520360.66     157879.89    1983546.29
2                    Cell phones    32624265.72     534502.03    6002147.63
3                      Computers    90619022.05     991605.47   11650867.21
4                 Games and Toys     1668574.13      24543.05     270374.96
5                Home Appliances    26607245.54     449373.36    5919992.87
6  Music, Movies and Audio Books    10588311.00     197246.13    2180768.13
7                   TV and Video    20466861.38     253806.81    4412178.23